service.name=marketing-integration-service
consul.service.name=${service.name}
consul.service.check.path=${service.name}/version
consul.service.enabled=false
consul.service.failOnRegistrationError=false